apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qprometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 72.5.0  # or latest version
    helm:
      values: |
        replicaCount: 1
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
